<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Qenta Payment CEE GmbH
 * (abbreviated to Qenta CEE) and are explicitly not part of the Qenta CEE range of
 * products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 2 (GPLv2) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Qenta CEE does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Qenta CEE does not guarantee their full
 * functionality neither does Qenta CEE assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Qenta CEE does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */
?>
<?php if ($this->getDataStorageUrl()): ?>
    <script type="text/javascript" src="<?php echo $this->getDataStorageUrl(); ?>"></script>
<?php endif; ?>
<script type="text/javascript"
        src="<?php echo Mage::getBaseUrl('js') . 'qenta/checkoutseamless/processing.js'; ?>"></script>
<script type="text/javascript">
    var qentaCheckoutSeamlessReadDatastorage = "<?php echo $this->getUrl('qenta_checkoutseamless/processing/readDatastorage', array("_secure" => true)); ?>";
    var qentaCheckoutSeamlessSaveSessInfo = "<?php echo $this->getUrl('qenta_checkoutseamless/processing/saveSessInfo', array("_secure" => true)); ?>";
    var qentaCheckoutSeamlessDeleteSessInfo = "<?php echo $this->getUrl('qenta_checkoutseamless/processing/deleteSessInfo', array("_secure" => true)); ?>";
    var qentaCheckoutSeamlessRedirectUrl = "<?php echo $this->getUrl('qenta_checkoutseamless/processing/getRedirectUrl', array("_secure" => true)); ?>";
</script>
<div class="window-overlay" id="window-overlay-qenta-checkoutseamless" style="display: none;"></div>
<div id="qenta-checkoutseamless-iframe-div" style="display: none">
    <div id="qenta-checkoutseamless-iframe-div-head">
        <h3><?php echo $this->__("Payment processing"); ?></h3>
    </div>
    <div id="qenta-checkoutseamless-iframe-div-body">
        <iframe src="about:blank" id="qenta-checkoutseamless-iframe"></iframe>
    </div>
</div>

<?php if (strlen($this->getConsumerDeviceId()) && $this->isRatepayPaymentProvider()) { ?>
    <!-- qenta checkout seamless device id script -->
    <script language="JavaScript">
        var di = {t:'<?php echo $this->getConsumerDeviceId(); ?>',v:'WDWL',l:'Checkout'};
    </script>
    <script type="text/javascript" src="//d.ratepay.com/<?php echo $this->getConsumerDeviceId(); ?>/di.js"></script>
    <noscript>
        <link rel="stylesheet" type="text/css" href="//d.ratepay.com/di.css?t=<?php echo $this->getConsumerDeviceId(); ?>&v=WDWL&l=Checkout">
    </noscript>
    <object type="application/x-shockwave-flash" data="//d.ratepay.com/WDWL/c.swf" width="0" height="0">
        <param name="movie" value="//d.ratepay.com/WDWL/c.swf" />
        <param name="flashvars" value="t=<?php echo $this->getConsumerDeviceId(); ?>&v=WDWL"/>
        <param name="AllowScriptAccess" value="always"/>
    </object>
    <!-- end of qenta checkout seamless device id script -->
<?php } ?>