<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard Central Eastern Europe GmbH
 * (abbreviated to Wirecard CEE) and are explicitly not part of the Wirecard CEE range of
 * products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 2 (GPLv2) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard CEE does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard CEE does not guarantee their full
 * functionality neither does Wirecard CEE assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard CEE does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */

$_code = $this->getMethod()->getFormCode();
$_data = $this->getSessionData();
$isDataSaved = !empty($_data);
if (!$isDataSaved) {
    $_data = array(
        'cc_owner'        => '',
        'cc_type'         => '',
        'cc_number'       => '',
        'cc_exp_month'    => '',
        'cc_exp_year'     => '',
    );
}
?>
<li id="wirecard_checkoutseamless_<?php echo $_code ?>_saved_data" <?php echo($isDataSaved ? '' : 'style="display:none;"'); ?>>
    <ul>
        <li>
            <label><?php echo $this->__('Cardholder Name') ?></label><br/>
            <span id="cardholdername"><?php echo $_data['cc_owner'] ?></span>
        </li>
        <li>
            <label><?php echo $this->__('Pan (for your protection only the last 4 numbers are saved)') ?></label><br/>
            <span id="anonymousPan"><?php echo $_data['cc_number'] ?></span>
        </li>
        <li>
            <label><?php echo $this->__('Expiration date') ?></label><br/>
            <span id="expiry"><?php echo $_data['cc_exp_month'] . '/' . $_data['cc_exp_year'] ?></span>
        </li>
    </ul>
    <a href="#payment"
       onclick="changePaymentData(); return false;"><?php echo $this->__('Change payment information') ?></a>
</li>


<li id="wirecard_checkoutseamless_<?php echo $_code ?>_new_data" <?php echo($isDataSaved ? 'style="display:none;"' : ''); ?>>
    <ul>
        <?php if ($this->showCardholder()): ?>
            <li>
                <label for="wirecard_checkoutseamless_<?php echo $_code ?>_cardholdername"><?php echo $this->__('Cardholder Name') ?>
                    <span class="required">*</span></label><br/>
                <input type="text" title="<?php echo $this->__('Cardholder Name') ?>"
                       class="required-entry input-text no-submit has-wcs-data" id="wirecard_checkoutseamless_<?php echo $_code ?>_cardholdername"
                       data-wcs-fieldname="cardholdername"
                       name="wirecard_checkoutseamless_<?php echo $_code ?>_cardholdername" value=""/>
            </li>
        <?php endif; ?>
        <li>
            <label for="wirecard_checkoutseamless_<?php echo $_code ?>_pan"><?php echo $this->__('Pan') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo $this->__('Pan') ?>" class="required-entry input-text no-submit has-wcs-data" data-wcs-fieldname="pan"
                   id="wirecard_checkoutseamless_<?php echo $_code ?>_pan" name="wirecard_checkoutseamless_<?php echo $_code ?>_pan" value=""/>
        </li>
        <li>
            <label for="wirecard_checkoutseamless_<?php echo $_code ?>_expirationMonth"><?php echo $this->__('Expiration date') ?> <span
                    class="required">*</span></label><br/>
            <select id="wirecard_checkoutseamless_<?php echo $_code ?>_expirationMonth"
                    name="wirecard_checkoutseamless_<?php echo $_code ?>_expirationMonth" class="required-entry no-submit month has-wcs-data"
                    data-wcs-fieldname="expirationMonth">
                <?php $_ccExpMonth = $this->getInfoData('wirecard_checkoutseamless_cc_expirationMonth') ?>
                <?php foreach ($this->getCcMonths() as $k => $v): ?>
                    <option
                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $this->getInfoData('wirecard_checkoutseamless_cc_expirationYear') ?>
            <select id="wirecard_checkoutseamless_<?php echo $_code ?>_expirationYear" name="wirecard_checkoutseamless_<?php echo $_code ?>_expirationYear"
                    class="required-entry no-submit year has-wcs-data" data-wcs-fieldname="expirationYear">
                <?php foreach ($this->getCcYears() as $k => $v): ?>
                    <option
                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
        </li>
        <?php if ($this->showCvc()): ?>
            <li>
                <label
                    for="wirecard_checkoutseamless_<?php echo $_code ?>_cardVerifyCode"><?php echo $this->__('Card Verify Code') ?></label><br/>
                <input type="text" title="<?php echo $this->__('Card Verify Code') ?>" class="input-text cvv no-submit has-wcs-data"
                       id="wirecard_checkoutseamless_<?php echo $_code ?>_cardVerifyCode" data-wcs-fieldname="cardVerifyCode"
                       name="wirecard_checkoutseamless_<?php echo $_code ?>_cardVerifyCode" value="" style="width:40px;"/>
            </li>
        <?php endif; ?>
        <?php if ($this->showIssueDate()): ?>
            <li>
                <label for="wirecard_checkoutseamless_<?php echo $_code ?>_issueMonth"><?php echo $this->__('Issue date') ?></label><br/>
                <select id="wirecard_checkoutseamless_<?php echo $_code ?>_issueMonth" name="wirecard_checkoutseamless_<?php echo $_code ?>_issueMonth"
                        class="no-submit month has-wcs-data" data-wcs-fieldname="issueMonth">
                    <?php $_ccIssMonth = $this->getInfoData('wirecard_checkoutseamless_cc_issueMonth') ?>
                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                        <option
                            value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccIssMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
                <?php $_ccIssYear = $this->getInfoData('wirecard_checkoutseamless_cc_issueYear') ?>
                <select id="wirecard_checkoutseamless_<?php echo $_code ?>_issueYear" name="wirecard_checkoutseamless_<?php echo $_code ?>_issueYear"
                        class="no-submit year has-wcs-data" data-wcs-fieldname="issueYear">
                    <?php foreach ($this->getSsStartYears() as $k => $v): ?>
                        <option
                            value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccIssYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </li>
        <?php endif; ?>
        <?php if ($this->showIssueNumber()): ?>
            <li>
                <label
                    for="wirecard_checkoutseamless_<?php echo $_code ?>_issueNumber"><?php echo $this->__('Card Issue Number') ?></label><br/>
                <input type="text" title="<?php echo $this->__('Card Issue Number') ?>" class="input-text cvv no-submit has-wcs-data"
                       id="wirecard_checkoutseamless_<?php echo $_code ?>_issueNumber" name="wirecard_checkoutseamless_<?php echo $_code ?>_issueNumber"
                       value="" style="width:40px;" data-wcs-fieldname="issueNumber"/>
            </li>
        <?php endif; ?>
    </ul>
</li>
<input type="hidden" value="<?php echo($isDataSaved ? '0' : '1'); ?>" name="wirecard_checkoutseamless_<?php echo $_code ?>_new"
       id="wirecard_checkoutseamless_<?php echo $_code ?>_new" autocomplete="off"/>
<input type="hidden" value="<?php echo $_data['cc_owner'] ?>" name="payment[cc_owner]" class="wcs-anon-data-hidden" autocomplete="off">
<input type="hidden" value="<?php echo $_data['cc_type'] ?>" name="payment[cc_type]" class="wcs-anon-data-hidden" autocomplete="off">
<input type="hidden" value="<?php echo $_data['cc_number'] ?>" name="payment[cc_number]" class="wcs-anon-data-hidden" autocomplete="off">
<input type="hidden" value="<?php echo $_data['cc_exp_month'] ?>" name="payment[cc_exp_month]" class="wcs-anon-data-hidden" autocomplete="off">
<input type="hidden" value="<?php echo $_data['cc_exp_year'] ?>" name="payment[cc_exp_year]" class="wcs-anon-data-hidden" autocomplete="off">
<input type="hidden" value="CCARD" class="wcs-paymentmethod" name="wirecard_checkoutseamless_<?php echo $_code ?>_type" autocomplete="off" />
