<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard Central Eastern Europe GmbH
 * (abbreviated to Wirecard CEE) and are explicitly not part of the Wirecard CEE range of
 * products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 2 (GPLv2) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard CEE does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard CEE does not guarantee their full
 * functionality neither does Wirecard CEE assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard CEE does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */
?>
<?php if ($this->getDataStorageUrl()): ?>
    <script type="text/javascript" src="<?php echo $this->getDataStorageUrl(); ?>"></script>
<?php endif; ?>
<script type="text/javascript"
        src="<?php echo Mage::getBaseUrl('js') . 'wirecard/checkoutseamless/processing.js'; ?>"></script>
<script type="text/javascript">
    var wirecardCheckoutSeamlessReadDatastorage = "<?php echo $this->getUrl('wirecard_checkoutseamless/processing/readDatastorage', array("_secure" => true)); ?>";
    var wirecardCheckoutSeamlessSaveSessInfo = "<?php echo $this->getUrl('wirecard_checkoutseamless/processing/saveSessInfo', array("_secure" => true)); ?>";
    var wirecardCheckoutSeamlessDeleteSessInfo = "<?php echo $this->getUrl('wirecard_checkoutseamless/processing/deleteSessInfo', array("_secure" => true)); ?>";
    var wirecardCheckoutSeamlessRedirectUrl = "<?php echo $this->getUrl('wirecard_checkoutseamless/processing/getRedirectUrl', array("_secure" => true)); ?>";
</script>
<div class="window-overlay" id="window-overlay-wirecard-checkoutseamless" style="display: none;"></div>
<div id="wirecard-checkoutseamless-iframe-div" style="display: none">
    <div id="wirecard-checkoutseamless-iframe-div-head">
        <h3><?php echo $this->__("Payment processing"); ?></h3>
    </div>
    <div id="wirecard-checkoutseamless-iframe-div-body">
        <iframe src="about:blank" id="wirecard-checkoutseamless-iframe"></iframe>
    </div>
</div>