<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard Central Eastern Europe GmbH
 * (abbreviated to Wirecard CEE) and are explicitly not part of the Wirecard CEE range of
 * products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 2 (GPLv2) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard CEE does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard CEE does not guarantee their full
 * functionality neither does Wirecard CEE assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard CEE does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */
?>
<li><label for="wirecard_checkoutseamless_invoice_dob_day" class="required"><em>*</em><?php echo $this->__('Date of Birth') ?></label>
    <div class="input-box wirecard-checkoutseamless-dob customer-dob">
        <div class="dob-day wirecard-checkoutseamless-invoice-dob-day">
            <input type="text" id="wirecard_checkoutseamless_invoice_dob_day"
                name="payment[wirecard_checkoutseamless_invoice_dob_day]"
                value="<?php echo $this->getCustomerDobDay() ?>"
                title="<?php echo $this->__('Day') ?>"
                class="input-text validate-custom" /> <label
                for="wirecard_checkoutseamless_invoice_dob_day"><?php echo $this->__('DD') ?></label>
        </div>
        <div class="dob-month wirecard-checkoutseamless-invoice-dob-month">
            <input type="text" id="wirecard_checkoutseamless_invoice_dob_month"
                name="payment[wirecard_checkoutseamless_invoice_dob_month]"
                value="<?php echo $this->getCustomerDobMonth() ?>"
                title="<?php echo $this->__('Month') ?>"
                class="input-text validate-custom" /> <label
                for="wirecard_checkoutseamless_invoice_dob_month"><?php echo $this->__('MM')  ?></label>
        </div>
        <div class="dob-year wirecard-checkoutseamless-invoice-dob-year">
            <input type="text" id="wirecard_checkoutseamless_invoice_dob_year"
                name="payment[wirecard_checkoutseamless_invoice_dob_year]"
                value="<?php echo $this->getCustomerDobYear() ?>"
                title="<?php echo $this->__('Year')  ?>"
                class="input-text validate-custom" /> <label
                for="wirecard_checkoutseamless_invoice_dob_year"><?php echo $this->__('YYYY') ?></label>
        </div>
        <div class="dob-full wirecard-checkoutseamless-invoice-dob-full" style="display: none;">
            <input type="hidden" id="wirecard_checkoutseamless_invoice_dob_full"
                name="payment[wirecard_checkoutseamless_invoice_dob]" />
        </div>

        <div class="validation-advice wirecard-checkoutseamless-invoice-validation-advice" id="wirecard_checkoutseamless_invoice_validation_advice" style="display: none;"></div>
    </div>
</li>

<script type="text/javascript">
    Translator.add('You have to be 18 years or older to use invoice payment.','<?php echo $this->__('You have to be 18 years or older to use invoice payment.')?>');
</script> <script type="text/javascript">
//<![CDATA[
Varien.QINVDateElement = Class.create();
Varien.QINVDateElement.prototype = Object.extend(new Varien.DateElement(), {
    validateData: function() {
        var year = this.fullDate.getFullYear();
        var date = new Date;
        this.curyear = date.getFullYear();
        if(year <= 1899 || year >= this.curyear+1)
        {
            return false;
        }
        var today = new Date();
        var limit = new Date((today.getFullYear() - 18), today.getMonth(), today.getDate());
        var validateToYoung = this.fullDate <= limit;
        this.validateDataErrorText = 'You have to be 18 years or older to use invoice payment.';
        return validateToYoung;
    }
});
Varien.QINVDOB = Class.create();
Varien.QINVDOB.prototype = {
    initialize: function(selector, required, format) {
        var el = $(selector);
        var container       = {};
        container.day       = Element.select(el, '#wirecard_checkoutseamless_invoice_dob_day')[0];
        container.month     = Element.select(el, '#wirecard_checkoutseamless_invoice_dob_month')[0];
        container.year      = Element.select(el, '#wirecard_checkoutseamless_invoice_dob_year')[0];
        container.full      = Element.select(el, '#wirecard_checkoutseamless_invoice_dob_full')[0];
        container.advice    = Element.select(el, '#wirecard_checkoutseamless_invoice_validation_advice')[0];

        new Varien.QINVDateElement('container', container, required, format);
    }
};

var wirecard_checkoutseamless_invoice_customer_dob = new Varien.QINVDOB('#payment_form_wirecard_checkoutseamless_invoice', 'true', '%y-%m-%d');
//]]>
</script>