<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard Central Eastern Europe GmbH
 * (abbreviated to Wirecard CEE) and are explicitly not part of the Wirecard CEE range of
 * products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 2 (GPLv2) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard CEE does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard CEE does not guarantee their full
 * functionality neither does Wirecard CEE assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard CEE does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */
?>
<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">

    <?php
    $_method = explode('_', $_code);
    $block = $this->getLayout()->createBlock($this->getSeamlessBlock($this->getMethod()->getFormCode()));
    $block->setMethod($this->getMethod());
    echo $block->toHtml();
    ?>

    <?php if ($this->hasPayolutionTerms()): ?>
        <label for="wirecard_checkoutpage_payolution_terms"
               class="required"><em>*</em><?php echo $this->__('Accept payolution terms') ?>:
        </label>

        <p class="control">
            <input type="checkbox" id="wirecard_checkoutpage_payolution_terms"
                   name="payment[wirecard_checkoutpage_payolution_terms]"
                   value="1"
                   title="<?php echo $this->__('payolution terms') ?>"
                   class="checkbox required-entry"/>
            <label
                for="wirecard_checkoutpage_payolution_terms"><?php echo sprintf($this->__('I agree that the data which are necessary for the liquidation of purchase on account and which are used to complete the identy and credit check are transmitted to payolution. My %s can be revoked at any time with effect for the future.'), $this->getPayolutionLink()); ?>
            </label>
        </p>
    <?php endif; ?>

    <?php if ($this->hasAdditionalForm()): ?>
        <?php echo $this->getLayout()->createBlock($this->getAdditionalForm())->toHtml(); ?>
    <?php endif; ?>
</ul>